### ISSUE TITLE
Frage zur Verwendung der Angabe im MessageHeader.Source bei Rezeptanforderung_besteatigung

### ISSUE THREAD

**Issue by KennySchueller** [gematik/spec-E-Rezept-ServiceRequest#53]
Liebe gematik-Kollegen,

beim Request für parenterale Zubereitungen muss im MessageHeader unter Source die Quellanwendung von der die Nachricht stammt angegeben werden. Beim Request ist dies die AVS Software. Muss bei der Response, also bei der Rezeptanforderung_besteatigung dann in diesem Knotenelement die Software des PVS angegeber werden, oder wieder die des AVS?

vielen Dank
viele Grüße
Kenny Schüller

**Comment by KennySchueller** [comment]
@florianschoffke ggf. können Sie hier für Klarheit sorgen :)

**Comment by florianschoffke** [comment]
Hallo @KennySchueller,

Das Projekt "ServiceRequest" setzt auf dem App Transport Framework auf. D.h. Vor- und Angaben wie das Bundle und der MessageHeader zu nutzen sind stammen aus diesem Projekt. Im dazugehörigen IG ist die Verwendung des MessageHeaders hier beschrieben: https://simplifier.net/guide/atf-implementation-guide/Home/UebergreifendeFestlegungen/Handshake.page.md?version=current

Der MessageHeader ist im Prinzip wie ein E-Mail Heder mit Sender, Empfänger und einer eindeutigen Message-ID. D.h. diese sind jedes mal entsprechend neu zu besetzen.
Falls die Angaben in dem IG nicht eindeutig sind gerne noch mal melden, dann können wir das entsprechend aufnehmen.

Ich hoffe, dass das für Klarheit gesorgt hat ;) 

Beste Grüße

**Comment by KennySchueller** [comment]
@florianschoffke Das hilft, vielen Dank für die Erläuterung.
