### ISSUE TITLE
Verwendung des Endpoint im MessageHeader

### ISSUE THREAD

**Issue by KennySchueller** [gematik/spec-E-Rezept-ServiceRequest#59]
Hallo Liebe gematik,

kurze Frage.
Im MessageHeader muss jedes sende System unter destination einen Endpoint angaben. Im Falle der Parenteralen Zubereitung, wo wir zuvor einen Request erhalten, müsste dieser in unserer Antwort der Endpoint aus der source der empfangen Nachricht entsprechen?
Ist unsere Annahme hier korrekt?

![image](https://github.com/gematik/spec-E-Rezept-ServiceRequest/assets/88763011/294c0a4d-12fc-4d42-b1e8-5b0458534d74)

In dem Zusammenhang stellt sich uns aber eine andere Frage.
Für die AVS Systeme ist es ja so gut wie nicht Möglich bei einem Request im MessageHeader unter <destination><endpoint> einen Wert anzugeben, da ggf. nicht bekannt ist welches System mit welchem Systemanbieter hier hinter der empfangenen KIM Adresse steckt.
Wie soll man darauf kommen?

Viele Grüße
Kenny Schüller

**Comment by florianschoffke** [comment]
Hallo Herr Schüller,
danke für das Finding, ich werde das intern abstimmen und Rückmeldung geben.

**Comment by florianschoffke** [comment]
Hallo Herr Schüller,

aufbauend auf Ihre Anfrage würden wir gerne folgendes anpassen:

- .endpoint ist die Angabe der KIM-Adresse mit dem Schema "mailto:<kim-adresse>"
- .sender.identifier und destination.receiver.identifier geben nun die TelematikID des Senders und Empfängers an

Diese Änderungen haben wir in diesem PR angegeben https://github.com/gematik/api-app-transport-framework/pull/52

Wäre das aus Ihrer Sicht ein gangbarer Weg für PS? 

Da das ein Breaking Change ist, wird das eine neue Version der Packages bedingen und die Implementierungen verändern.

**Comment by florianschoffke** [comment]
Wird im ATF angepasst. Ein neues Package für das ATF und die Rezeptanforderung folgen.
