### ISSUE TITLE
Test KIM-Adressen in der RU

### ISSUE THREAD

**Issue by zarmalkashefy** [gematik/spec-E-Rezept-ServiceRequest#62]
### Discussed in https://github.com/gematik/spec-E-Rezept-ServiceRequest/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **florianschoffke** March 12, 2024</sup>
## Testing von Rezeptanforderungen
Hersteller können KIM-Test Adressen in der RU anbieten, um ihre eigene Anwendung zu härten und auch anderen die Möglichkeit geben zu entwickeln. Hierzu bitte einen Post erstellen mit dem Label "🙌 Show and Tell" und folgende Informationen angeben:

- Hersteller
- Kontaktmöglichkeit
- Art des PS
- KIM-Adresse(n)
- Unterstützte Anwendungsfälle

Wir veröffentlichen den Eintrag dann in der untenstehenden Tabelle.

## Liste der verfügbaren KIM-Adressen

| Hersteller | Kontakt | Art des PS | KIM-Adresse | Unterstützte Anwendungsfälle |
|--------|--------|--------|--------|
| gemtikBeispiel | info@gematik.de | AVS | test@kim.gematik.beispiel.de | eRezept_Rezeptanforderung; eRezept_ParenteraleZubereitung|</div>

**Comment by zarmalkashefy** [comment]
Hallo Herr Schoffke, bitte nehmen Sie uns hier in die Liste auf. Danke :)

NOVENTI-ApoFAKT I Zarmal Kashefy [Zarmal.Kashefy@Noventi.de](mailto:Zarmal.Kashefy@Noventi.de) I AVS/Tax-Software I   
testcenter-0539@cgm-ref.komle.telematik-test I eRezept_Rezeptanforderung; eRezept_ParenteraleZubereitung|

**Comment by bNaumann-gem** [comment]
Habe ich in der Discussion eingefügt
