### ISSUE TITLE
Anpassung IG: Menge Rezeptanforderung pro KIM

### ISSUE THREAD

**Issue by bNaumann-gem** [gematik/spec-E-Rezept-ServiceRequest#64]
Der Implementation Guide 'Kommunikation für das E-Rezept' schreibt unter "Einführung" - "Allgemeine Festlegungen" - "Anzahl von E-Rezepten pro Nachricht" vor, dass eine Nachricht nur ein Rezept adressiert. Dieser Abschnitt muss noch angepasst werden.

_Originally posted by @omeiners in https://github.com/gematik/spec-E-Rezept-ServiceRequest/discussions/63#discussioncomment-8773738_

**Comment by florianschoffke** [comment]
Korrektur wurde gemerged
